# -*- coding: utf-8 -*-
"""app.py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lyrbPuQaJiBIUrq0fwXTJmjIDDcL106
"""

!pip install streamlit
# !pip install pyngrok

import streamlit as st
import joblib
import numpy as np

# Load model & vectorizer
model = joblib.load("sentiment_model.pkl")
vectorizer = joblib.load("vectorizer.pkl")

# ---- Page Config ----
st.set_page_config(
    page_title="News Sentiment Classifier",
    page_icon="📰",
    layout="centered",
)

# ---- Custom CSS ----
st.markdown("""
<style>

body {
    background-color: #f2f4f7;
}

.card {
    background-color: white;
    padding: 25px;
    border-radius: 12px;
    box-shadow: 0px 0px 18px rgba(0,0,0,0.08);
}

.result-box {
    padding: 15px;
    border-radius: 10px;
    text-align: center;
    font-size: 22px;
    font-weight: 600;
}

.positive { background-color: #d4edda; color: #155724; }
.negative { background-color: #f8d7da; color: #721c24; }
.neutral  { background-color: #fff3cd; color: #856404; }

</style>
""", unsafe_allow_html=True)

# ---- Main Heading ----
st.markdown("<h1 style='text-align:center; margin-bottom:5px;'>📰 News Sentiment Classifier</h1>", unsafe_allow_html=True)
st.markdown("<p style='text-align:center; color:gray; margin-top:-10px;'>Analyze the sentiment of any news headline instantly</p>", unsafe_allow_html=True)

# ---- Card Container ----
st.markdown("<div class='card'>", unsafe_allow_html=True)

# Text Input
text_input = st.text_area(
    "Enter a News Headline",
    placeholder="Example: 'Stock markets rise after new economic reforms'",
    height=120
)

# Predict button
btn = st.button("Analyze Sentiment")

# ---- Prediction Logic ----
if btn:
    if text_input.strip() == "":
        st.warning("Please enter a news headline.")
    else:
        vec = vectorizer.transform([text_input])
        pred = model.predict(vec)[0]

        # UI result box
        if pred == "positive":
            color_class = "positive"
            label = "Positive 🔥"
        elif pred == "negative":
            color_class = "negative"
            label = "Negative ⚠️"
        else:
            color_class = "neutral"
            label = "Neutral 🟡"

        st.markdown(
            f"<div class='result-box {color_class}'>{label}</div>",
            unsafe_allow_html=True
        )

st.markdown("</div>", unsafe_allow_html=True)